/**
 * sw.js — Service Worker for the SAC Chronicle.
 *
 * What it is for: repeat visits and flaky connections. Code (HTML, CSS, JS) is
 * fetched live and kept as an offline fallback; media is served from cache and
 * refreshed behind the reader (stale-while-revalidate); the asset map is
 * network-first.
 *
 * What it deliberately does NOT do: precache the site. It used to fetch ~100
 * files (1.7 MB — every page, every script, five paper textures and a 469 KB
 * audio track) the moment it installed, which on a phone ran *during* the
 * page's own first paint and slowed it down. Now only the small app shell is
 * installed; every other page, picture and script is cached the first time it
 * is actually used.
 */

const CACHE_NAME = "sac-v54";

/* The app shell: the pages' shared CSS and the modules every page loads.
 * Generated from the real import graph — run `node tools/sync-pages.mjs`
 * after changing what main.js imports. */
/* shell:start (generated by tools/sync-pages.mjs — do not edit) */
const SHELL = [
  "index.html",
  "404.html",
  "css/preloader.css",
  "css/reset.css",
  "css/variables.css",
  "css/main.css",
  "css/components.css",
  "css/enhancements.css",
  "css/loader.css",
  "css/settings.css",
  "css/viewer.css",
  "js/main.js",
  "js/utils/dom.js",
  "js/components/navbar.js",
  "js/config.js",
  "js/components/footer.js",
  "js/data/clubs.js",
  "js/components/navbar-fold.js",
  "js/components/search-launcher.js",
  "js/components/settings.js",
  "js/utils/calligraphy.js",
  "js/utils/music.js",
  "js/loader.js",
  "js/components/back-to-top.js",
  "js/utils/view-pref.js",
];
/* shell:end */

const DYNAMIC_ASSETS = ["public/assets/processed/assets_map.jsonl"];

/* The repo is mirrored under different path casings — /SAC_website/ on the
 * primary Pages domain, /SAC_Website/ on the secondary — so never hard-code
 * one: derive the deployment prefix from the worker's own scope. Resolves
 * to "/" for custom-domain roots, which correctly matches everything. */
const SCOPE_PATH = new URL(self.registration.scope).pathname;

/* Code is network-first (see the fetch handler): a deploy must never leave a
 * reader with fresh markup and stale scripts. */
const CODE_RE = /\.(?:html|css|js)$/i;

/* -------------------------------------------------------------------------
 * Install — cache the app shell only
 * ------------------------------------------------------------------------- */

self.addEventListener("install", (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(SHELL).catch((err) => {
        // A missing shell file must not stop the worker from installing.
        console.warn("[SW] Some shell files failed to cache:", err);
      });
    })
  );
});

/* -------------------------------------------------------------------------
 * Activate — clean old caches
 * ------------------------------------------------------------------------- */

self.addEventListener("activate", (event) => {
  self.clients.claim();
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)));
    })
  );
});

/* -------------------------------------------------------------------------
 * Fetch — serve from cache first, fall back to network
 * ------------------------------------------------------------------------- */

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);

  // Only handle same-origin requests
  if (url.origin !== self.location.origin) return;

  // Dynamic assets (JSONL, markdown) — network first, cache fallback
  if (DYNAMIC_ASSETS.some((path) => url.pathname.endsWith(path))) {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
          return response;
        })
        .catch(() => caches.match(event.request))
    );
    return;
  }

  // Code (HTML, CSS, JS, and navigations) — network first, cache fallback.
  // A deploy once left readers with fresh HTML and stale scripts: the gallery
  // layout toggle shipped, appeared in the markup, and did nothing until a
  // second reload (2026-09-21). Fetching code live costs a few ms on Pages
  // and removes that whole class of mixed-version bugs. Media below stays
  // stale-while-revalidate so grids stay instant and work offline.
  if (CODE_RE.test(url.pathname) || url.pathname.endsWith("/")) {
    event.respondWith(
      fetch(event.request)
        .then((response) => {
          if (response.ok && url.pathname.startsWith(SCOPE_PATH)) {
            const clone = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
          }
          return response;
        })
        .catch(() => caches.match(event.request))
    );
    return;
  }

  // Static assets — stale-while-revalidate: serve from cache instantly,
  // update cache from network in the background so next load is fresh.
  event.respondWith(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.match(event.request).then((cached) => {
        const networkFetch = fetch(event.request)
          .then((response) => {
            if (response.ok && url.pathname.startsWith(SCOPE_PATH)) {
              cache.put(event.request, response.clone());
            }
            return response;
          })
          .catch(() => cached);
        return cached || networkFetch;
      });
    })
  );
});
