#!/usr/bin/env node
/**
 * tools/gen-sitemap.mjs — sitemap.xml and robots.txt for the host being deployed to.
 *
 * Why this is generated. The repo is deployed from two GitHub accounts, each
 * with its own Pages host and its own path casing:
 *
 *   https://shuvam-banerji-seal.github.io/SAC_Website/
 *   https://slashdot-iiserk.github.io/SAC_website/        (lowercase w)
 *
 * A sitemap is only valid for URLs on the host that serves it, and Pages paths
 * are case-sensitive. The hand-written sitemap listed /SAC_Website/ URLs on the
 * slashdot host, where every one of them is a 404 — so crawlers got nothing.
 * One checked-in file cannot be right for both hosts; CI builds it from the
 * base URL of the deployment it is publishing (actions/configure-pages exposes
 * it as `base_url`).
 *
 *   node tools/gen-sitemap.mjs                        defaults to this repo's own Pages URL
 *   node tools/gen-sitemap.mjs --base https://h/Path  a specific deployment
 *   node tools/gen-sitemap.mjs --out _site            write somewhere other than the repo root
 *
 * `lastmod` is the date of the last commit that touched each page, so it moves
 * when a page does — not when someone remembers to edit a date.
 */
import { execFileSync } from "node:child_process";
import { readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const DEFAULT_BASE = "https://shuvam-banerji-seal.github.io/SAC_Website";

/** Pages that are navigation targets, not club records. */
const SECTION_PAGES = new Set([
  "pages/about.html",
  "pages/clubs.html",
  "pages/events.html",
  "pages/gallery.html",
  "pages/campus-life.html",
]);

/** Strip trailing slashes so `${base}/x` never doubles up. */
export const normalizeBase = (base) => String(base).trim().replace(/\/+$/, "");

/** Every page the site serves, as repo-relative paths. The 404 page is not indexable. */
export function pageList(root = ROOT) {
  return [
    "index.html",
    ...readdirSync(resolve(root, "pages"))
      .filter((f) => f.endsWith(".html"))
      .sort()
      .map((f) => `pages/${f}`),
  ];
}

/** The public URL of a page: the home page is the site root, with no index.html. */
export function urlFor(base, page) {
  const b = normalizeBase(base);
  return page === "index.html" ? `${b}/` : `${b}/${page}`;
}

function profile(page) {
  if (page === "index.html") return { changefreq: "weekly", priority: "1.0" };
  if (SECTION_PAGES.has(page)) return { changefreq: "weekly", priority: "0.8" };
  return { changefreq: "monthly", priority: "0.6" };
}

/** Date (YYYY-MM-DD) of the last commit touching `page`; today if git has no answer. */
export function lastModified(page, root = ROOT) {
  try {
    const out = execFileSync("git", ["log", "-1", "--format=%cs", "--", page], {
      cwd: root,
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (out) return out;
  } catch {
    /* not a git checkout — fall through */
  }
  return statSync(resolve(root, page)).mtime.toISOString().slice(0, 10);
}

const escapeXml = (s) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/** @param {string} base @param {string[]} pages @param {(page: string) => string} lastmodOf */
export function buildSitemap(base, pages, lastmodOf) {
  const entries = pages.map((page) => {
    const { changefreq, priority } = profile(page);
    return [
      "  <url>",
      `    <loc>${escapeXml(urlFor(base, page))}</loc>`,
      `    <lastmod>${lastmodOf(page)}</lastmod>`,
      `    <changefreq>${changefreq}</changefreq>`,
      `    <priority>${priority}</priority>`,
      "  </url>",
    ].join("\n");
  });
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries,
    "</urlset>",
    "",
  ].join("\n");
}

export function buildRobots(base) {
  return [
    "User-agent: *",
    "Allow: /",
    "",
    "# Generated by tools/gen-sitemap.mjs for the host this copy is served from.",
    `Sitemap: ${normalizeBase(base)}/sitemap.xml`,
    "",
  ].join("\n");
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const arg = (name) => {
    const i = process.argv.indexOf(name);
    return i > -1 ? process.argv[i + 1] : undefined;
  };
  const base = normalizeBase(arg("--base") || DEFAULT_BASE);
  const out = resolve(ROOT, arg("--out") || ".");
  mkdirSync(out, { recursive: true });
  const pages = pageList();
  writeFileSync(
    resolve(out, "sitemap.xml"),
    buildSitemap(base, pages, (p) => lastModified(p))
  );
  writeFileSync(resolve(out, "robots.txt"), buildRobots(base));
  console.log(`sitemap.xml (${pages.length} URLs) and robots.txt written to ${out}`);
  console.log(`base: ${base}`);
}
