#!/usr/bin/env node
/**
 * tools/sync-pages.mjs — keep every page's <head> in step with the module graph.
 *
 * Why. ES modules are discovered one level at a time: the browser fetches
 * main.js, parses it, discovers its imports, fetches those, parses them … On a
 * phone with a 150 ms round trip every level of that chain is another 150 ms
 * before the page can start. A <link rel="modulepreload"> for every module the
 * page is certain to need lets the browser fetch the whole graph in one round.
 *
 * Writing 14 of those by hand into 38 pages is how they go stale, so they are
 * generated here, between markers, from the real import graph:
 *
 *   <!-- preload:start (generated by tools/sync-pages.mjs — do not edit) -->
 *   <link rel="modulepreload" href="js/main.js" /> …
 *   <script type="module" src="js/main.js"></script>
 *   <!-- preload:end -->
 *
 * The entry <script> lives in the head too (module scripts are deferred, so it
 * still runs after the document is parsed) — its fetch now starts with the
 * HTML instead of after the last byte of it.
 *
 * Club pages also get two blocks derived from the club registry
 * (js/data/clubs.js), so they are static HTML — no layout shift, and they work
 * without JavaScript:
 *   club-crumbs   the breadcrumb:  Home › Clubs › SAC Cultural › AARSHI
 *   club-pager    "More from SAC Cultural" and previous / next club
 *
 * The home page gets one more from the same registry:
 *   home-finder   "What are you into?" — an interest chip per INTERESTS row, with its club count
 *
 * The same graph defines the service worker's app shell (SHELL in sw.js), so
 * what is installed up front is exactly what every page needs — nothing more.
 *
 *   node tools/sync-pages.mjs          rewrite the pages and sw.js
 *   node tools/sync-pages.mjs --check  exit 1 if anything is out of date
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { dirname, resolve, posix } from "node:path";
import { BODIES, CLUBS, INTERESTS, bodyById, clubByPage } from "../js/data/clubs.js";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const START = "<!-- preload:start (generated by tools/sync-pages.mjs — do not edit) -->";
const END = "<!-- preload:end -->";

/** Modules each page type loads on top of the shared shell (main.js's closure). */
export const PAGE_MODULES = {
  home: [
    "js/pages/home.js",
    // loaded by home.js right after the archive arrives — worth having in flight
    "js/components/sac-diagram.js",
    "js/components/campus-book.js",
    "js/components/campus-board.js",
  ],
  clubs: ["js/pages/clubs.js", "js/components/section-nav.js"],
  events: ["js/pages/events.js"],
  gallery: ["js/pages/gallery.js"],
  "campus-life": ["js/pages/campus-life.js"],
  about: ["js/components/council-facts.js"],
  club: ["js/pages/club-page.js", "js/pages/club-images.js", "js/components/section-nav.js"],
};

const STATIC_IMPORT = /(?:^|\n)\s*(?:import|export)\s+(?:[^'"()]*?\sfrom\s+)?["']([^"']+)["']/g;

/** Static (non-dynamic) relative imports of a module, as repo-relative paths. */
export function staticImports(file, root = ROOT) {
  const src = readFileSync(resolve(root, file), "utf-8");
  const out = [];
  for (const m of src.matchAll(STATIC_IMPORT)) {
    const spec = m[1];
    if (!spec.startsWith(".")) continue; // bare/CDN specifiers are not ours to preload
    out.push(posix.normalize(posix.join(posix.dirname(file), spec)));
  }
  return out;
}

/** Every module reachable from `entries` by static imports, entry order first. */
export function closure(entries, root = ROOT) {
  const seen = new Set();
  const order = [];
  const visit = (file) => {
    if (seen.has(file) || !existsSync(resolve(root, file))) return;
    seen.add(file);
    order.push(file);
    for (const dep of staticImports(file, root)) visit(dep);
  };
  entries.forEach(visit);
  return order;
}

/** The page type from the document: <body data-page="…"> (club pages say "club"). */
export function pageTypeOf(html) {
  return html.match(/<body[^>]*\sdata-page="([^"]+)"/)?.[1] || null;
}

/** The generated head block for one page. `prefix` is "" or "../". */
export function buildBlock(pageType, prefix, root = ROOT) {
  const modules = closure(["js/main.js", ...(PAGE_MODULES[pageType] || [])], root);
  // a page-type's own modules may themselves import more of the graph
  const links = modules.map((m) => `    <link rel="modulepreload" href="${prefix}${m}" />`);
  return [
    `    ${START}`,
    ...links,
    `    <script type="module" src="${prefix}js/main.js"></script>`,
    `    ${END}`,
  ].join("\n");
}

/* ------------------------------------------------------------------ club pages */

const CRUMBS_START = "<!-- club-crumbs:start (generated by tools/sync-pages.mjs — do not edit) -->";
const CRUMBS_END = "<!-- club-crumbs:end -->";
const PAGER_START = "<!-- club-pager:start (generated by tools/sync-pages.mjs — do not edit) -->";
const PAGER_END = "<!-- club-pager:end -->";
const FINDER_START = "<!-- home-finder:start (generated by tools/sync-pages.mjs — do not edit) -->";
const FINDER_END = "<!-- home-finder:end -->";

const esc = (t) => String(t).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const fileOf = (club) => club.page.replace(/^pages\//, "");

/** The directory's order: body by body, registry order within each. */
export function directoryOrder() {
  return BODIES.flatMap((b) => CLUBS.filter((c) => c.body === b.id));
}

/** Home › Clubs › <body> › <club>. Paths are relative to pages/. */
export function buildCrumbs(club, indent = "        ") {
  const body = bodyById(club.body);
  const lines = [
    '<nav class="crumbs" aria-label="Breadcrumb">',
    '  <ol class="crumbs__list">',
    '    <li><a href="../index.html">Home</a></li>',
    '    <li><a href="clubs.html">Clubs</a></li>',
    `    <li><a href="clubs.html#body-${body.id}">${esc(body.label)}</a></li>`,
    `    <li aria-current="page">${esc(club.short)}</li>`,
    "  </ol>",
    "</nav>",
  ];
  return [CRUMBS_START, ...lines, CRUMBS_END].map((l) => indent + l).join("\n");
}

/** Up to `n` other clubs from the same body, starting after this one so every club gets a different neighbour set. */
export function relatedClubs(club, n = 4) {
  const peers = CLUBS.filter((c) => c.body === club.body);
  const at = peers.findIndex((c) => c.slug === club.slug);
  const out = [];
  for (let i = 1; i < peers.length && out.length < n; i++) out.push(peers[(at + i) % peers.length]);
  return out;
}

/** "More from <body>" (or, for a body of one, the other bodies), and previous / next. */
export function buildPager(club, indent = "        ") {
  const body = bodyById(club.body);
  const related = relatedClubs(club);
  const order = directoryOrder();
  const at = order.findIndex((c) => c.slug === club.slug);
  const prev = order[at - 1];
  const next = order[at + 1];

  const chip = (c) =>
    `    <li><a href="${fileOf(c)}" data-logo-for="${esc(c.slug)}"><span class="club-pager__logo" aria-hidden="true"></span><span class="club-pager__name">${esc(c.short)}</span></a></li>`;
  const bodyChip = (b) =>
    `    <li><a href="clubs.html#body-${b.id}"><span class="club-pager__name">${esc(b.label)}</span></a></li>`;

  const lines = ['<nav class="club-pager" aria-label="More clubs" data-no-jump>'];
  if (related.length >= 2) {
    lines.push(
      `  <h2 class="club-pager__title">More from ${esc(body.label)}</h2>`,
      '  <ul class="club-pager__related">',
      ...related.map(chip),
      "  </ul>"
    );
  } else {
    lines.push(
      '  <h2 class="club-pager__title">Elsewhere in the Council</h2>',
      '  <ul class="club-pager__related club-pager__related--bodies">',
      ...BODIES.filter((b) => b.id !== club.body).map(bodyChip),
      "  </ul>"
    );
  }
  lines.push('  <div class="club-pager__step">');
  lines.push(
    prev
      ? `    <a class="club-pager__prev" rel="prev" href="${fileOf(prev)}"><span>Previous</span> ${esc(prev.short)}</a>`
      : '    <span class="club-pager__prev" aria-hidden="true"></span>'
  );
  lines.push(
    next
      ? `    <a class="club-pager__next" rel="next" href="${fileOf(next)}"><span>Next</span> ${esc(next.short)}</a>`
      : '    <span class="club-pager__next" aria-hidden="true"></span>'
  );
  lines.push("  </div>", "</nav>");
  return [PAGER_START, ...lines, PAGER_END].map((l) => indent + l).join("\n");
}

/**
 * The home page's "What are you into?" section: one chip per interest, each a plain link to
 * the Clubs page filtered to it (so it works without JavaScript), a search button, and the
 * empty mount the "club of the day" fills. Static, so it costs no layout shift.
 */
export function buildFinder(indent = "      ") {
  const count = (id) => CLUBS.filter((c) => c.interests.includes(id)).length;
  const chip = (i) =>
    `    <li><a class="finder__chip" href="pages/clubs.html?interest=${i.id}">${esc(i.label)}<span class="finder__count">${count(i.id)}<span class="visually-hidden"> clubs</span></span></a></li>`;
  const lines = [
    '<section class="finder reveal-section" aria-labelledby="finder-title">',
    '  <h2 id="finder-title" class="section-title">What are you into?</h2>',
    '  <p class="finder__lede">',
    "    Pick what pulls you and the Chronicle lists the clubs to meet &mdash; or just start typing a name.",
    "  </p>",
    '  <ul class="finder__chips">',
    ...INTERESTS.map(chip),
    "  </ul>",
    '  <button class="finder__search" type="button" data-open-search aria-keyshortcuts="/ Control+K Meta+K">',
    '    <span class="finder__search-glyph" aria-hidden="true">&#8981;</span>',
    "    <span>Search clubs and pages</span>",
    '    <kbd class="finder__kbd" aria-hidden="true">/</kbd>',
    "  </button>",
    '  <div id="club-spotlight" class="spotlight" role="group" aria-label="Club of the day"></div>',
    "</section>",
  ];
  return [FINDER_START, ...lines, FINDER_END].map((l) => indent + l).join("\n");
}

/** The home page's generated block. Returns the html unchanged for any other page. */
export function syncHomeBlocks(html, file) {
  if (file !== "index.html") return html;
  return placeBlock(
    html,
    FINDER_START,
    FINDER_END,
    buildFinder(),
    /[ \t]*<div class="paper-tear" aria-hidden="true"><\/div>/
  );
}

/** Replace or insert a generated block. `anchor` is where it goes the first time. */
function placeBlock(html, start, end, block, anchor) {
  const existing = new RegExp(`[ \\t]*${escapeRe(start)}[\\s\\S]*?${escapeRe(end)}`);
  if (existing.test(html)) return html.replace(existing, () => block);
  return html.replace(anchor, (m) => `${block}\n${m}`);
}

/** The club page's two generated blocks. Returns the html unchanged for any other page. */
export function syncClubBlocks(html, file) {
  const club = clubByPage(file);
  if (!club || !/data-club-slug=/.test(html)) return html;
  let next = placeBlock(
    html,
    CRUMBS_START,
    CRUMBS_END,
    buildCrumbs(club),
    /[ \t]*<header class="club-detail__header">/
  );
  next = placeBlock(next, PAGER_START, PAGER_END, buildPager(club), /[ \t]*<\/article>/);
  return next;
}

/** Rewrite one HTML document; returns the new text (unchanged if already current). */
export function syncHtml(html, prefix, root = ROOT) {
  const type = pageTypeOf(html);
  if (!type || !(type in PAGE_MODULES)) return html;
  const block = buildBlock(type, prefix, root);

  // Start from a clean slate so the result never depends on what was there:
  // drop a previously generated block, then any hand-written entry script
  // (the legacy one sat at the end of <body>).
  const generated = new RegExp(`[ \\t]*${escapeRe(START)}[\\s\\S]*?${escapeRe(END)}[ \\t]*\\n`);
  const legacy = /[ \t]*<script type="module" src="(?:\.\.\/)?js\/main\.js"><\/script>[ \t]*\n/g;
  const clean = html.replace(generated, "").replace(legacy, "");

  // Insert before the favicon (the last thing in every <head>), else before </head>.
  const anchor = /\n[ \t]*<link\s+rel="icon"/;
  if (anchor.test(clean)) return clean.replace(anchor, (m) => `\n${block}${m}`);
  return clean.replace(/\n[ \t]*<\/head>/, (m) => `\n${block}${m}`);
}

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/** All pages that carry the shell: index.html and pages/*.html (404 is self-contained). */
export function pageFiles(root = ROOT) {
  return [
    "index.html",
    ...readdirSync(resolve(root, "pages"))
      .filter((f) => f.endsWith(".html"))
      .map((f) => `pages/${f}`),
  ];
}

/** Stylesheets every page shares: index.html's own <link>s minus per-page and print CSS. */
export function coreCss(root = ROOT) {
  const html = readFileSync(resolve(root, "index.html"), "utf-8");
  return [...html.matchAll(/<link rel="stylesheet" href="(css\/[^"]+)"(?![^>]*media="print")/g)]
    .map((m) => m[1])
    .filter((href) => !href.startsWith("css/pages/"));
}

/** The service worker's app shell: the home document, the offline page, shared CSS, the entry graph. */
export function buildShell(root = ROOT) {
  return ["index.html", "404.html", ...coreCss(root), ...closure(["js/main.js"], root)];
}

const SHELL_RE = /\/\* shell:start[^*]*\*\/\n[\s\S]*?\/\* shell:end \*\//;

/** Rewrite the SHELL block of sw.js; returns the new text. */
export function syncServiceWorker(js, root = ROOT) {
  const list = buildShell(root)
    .map((f) => `  "${f}",`)
    .join("\n");
  const block = `/* shell:start (generated by tools/sync-pages.mjs — do not edit) */\nconst SHELL = [\n${list}\n];\n/* shell:end */`;
  return js.replace(SHELL_RE, () => block);
}

export function run({ check = false, root = ROOT } = {}) {
  const stale = [];
  for (const file of pageFiles(root)) {
    const path = resolve(root, file);
    const html = readFileSync(path, "utf-8");
    const prefix = file.startsWith("pages/") ? "../" : "";
    const next = syncHomeBlocks(syncClubBlocks(syncHtml(html, prefix, root), file), file);
    if (next !== html) {
      stale.push(file);
      if (!check) writeFileSync(path, next);
    }
  }
  const sw = resolve(root, "sw.js");
  if (existsSync(sw)) {
    const js = readFileSync(sw, "utf-8");
    const next = syncServiceWorker(js, root);
    if (next !== js) {
      stale.push("sw.js");
      if (!check) writeFileSync(sw, next);
    }
  }
  return stale;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  const stale = run({ check });
  if (check && stale.length) {
    console.error(
      `generated blocks out of date in ${stale.length} page(s):\n  ${stale.join("\n  ")}`
    );
    console.error("run: node tools/sync-pages.mjs");
    process.exit(1);
  }
  console.log(
    check
      ? `generated blocks up to date (${pageFiles().length} pages)`
      : `updated ${stale.length} of ${pageFiles().length} pages`
  );
}
