/**
 * test/unit/load-budget.test.js — what a page is allowed to load before it can paint.
 *
 * Every page used to import every other page's script, register the service
 * worker mid-load (its install fetched ~1.7 MB behind the page), and discover
 * its modules one network round at a time. These tests keep it from drifting
 * back: they are about *structure*, not byte counts, so they stay valid as the
 * code grows.
 */
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import {
  closure,
  staticImports,
  run,
  pageFiles,
  pageTypeOf,
  PAGE_MODULES,
} from "../../tools/sync-preloads.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const read = (rel) => readFileSync(resolve(root, rel), "utf-8");

describe("entry script", () => {
  const main = read("js/main.js");

  it("statically imports no page module — pages are loaded one at a time", () => {
    const statics = staticImports("js/main.js");
    expect(statics.filter((m) => m.startsWith("js/pages/"))).toEqual([]);
    // …and the page modules it does start are dynamic imports
    for (const page of ["home", "clubs", "events", "gallery", "campus-life"]) {
      expect(main).toContain(`import("./pages/${page}.js")`);
    }
    expect(main).toContain('import("./pages/club-page.js")');
    expect(main).toContain('import("./pages/club-images.js")');
  });

  it("keeps the heavyweight, rarely-needed modules out of the shell", () => {
    const shell = closure(["js/main.js"]);
    for (const heavy of [
      "js/components/viewer.js", // lightbox: idle, before the first click
      "js/utils/text-measure.js", // pulls in the whole pretext library
      "js/data.js", // the 2 MB archive belongs to the pages that use it
      "js/components/calendar.js",
      "js/components/campus-book.js",
    ]) {
      expect(shell, `${heavy} must not be in every page's critical path`).not.toContain(heavy);
    }
    expect(shell.some((f) => f.startsWith("js/pretext/"))).toBe(false);
    expect(shell.length).toBeLessThanOrEqual(14);
  });

  it("defers the lightbox, music and reading progress to idle time", () => {
    expect(main).toMatch(
      /whenIdle\(async \(\) => \{[\s\S]*viewer\.js[\s\S]*music\.js[\s\S]*reading-progress\.js/
    );
    expect(staticImports("js/main.js")).not.toContain("js/components/viewer.js");
  });

  it("registers the service worker after load, when idle — never during first paint", () => {
    expect(main).toContain('window.addEventListener("load", register');
    expect(main).toContain("navigator.serviceWorker.register(swUrl)");
    // the registration call sits inside a whenIdle() callback
    expect(main).toMatch(/whenIdle\(\(\) => \{[\s\S]*serviceWorker\.register/);
  });

  it("the council facts need no data, so About does not download the archive for them", () => {
    expect(staticImports("js/components/council-facts.js")).not.toContain("js/data.js");
    expect(main).toContain("council-facts.js");
    expect(main).not.toContain("renderArchiveStats");
  });
});

describe("module preload hints (generated by tools/sync-preloads.mjs)", () => {
  it("every page is up to date with the real import graph", () => {
    // run({check:true}) reports the pages it WOULD change; none may be stale.
    expect(run({ check: true })).toEqual([]);
  });

  it("every page loads main.js once, from the head, and not at the end of <body>", () => {
    for (const file of pageFiles()) {
      const html = read(file);
      const head = html.slice(0, html.indexOf("</head>"));
      const body = html.slice(html.indexOf("</head>"));
      const entry = /<script type="module" src="(?:\.\.\/)?js\/main\.js"><\/script>/g;
      expect((head.match(entry) || []).length, `${file}: one entry script in <head>`).toBe(1);
      expect((body.match(entry) || []).length, `${file}: none after </head>`).toBe(0);
    }
  });

  it("each page preloads exactly its own module, not its neighbours'", () => {
    const home = read("index.html");
    expect(home).toContain('href="js/pages/home.js"');
    expect(home).not.toContain("js/pages/gallery.js");
    const club = read("pages/aarshi.html");
    expect(club).toContain('href="../js/pages/club-page.js"');
    expect(club).toContain('href="../js/pages/club-images.js"');
    expect(club).not.toContain("js/pages/home.js");
  });

  it("every page type in the site is covered by the generator", () => {
    const types = new Set(pageFiles().map((f) => pageTypeOf(read(f))));
    for (const t of types) expect(Object.keys(PAGE_MODULES), `page type "${t}"`).toContain(t);
  });

  it("preload paths all resolve to files that exist", () => {
    for (const file of pageFiles()) {
      for (const [, href] of read(file).matchAll(
        /rel="modulepreload" href="((?:\.\.\/)?js\/[^"]+)"/g
      )) {
        const rel = href.replace(/^\.\.\//, "");
        expect(() => read(rel), `${file} preloads ${rel}`).not.toThrow();
      }
    }
  });
});

describe("service worker precache", () => {
  const sw = read("sw.js");
  const shell = JSON.parse(
    "[" + (sw.match(/const SHELL = \[([\s\S]*?)\];/)?.[1] || "").replace(/,\s*$/, "") + "]"
  );

  it("installs only the app shell — a few dozen small files, not the site", () => {
    expect(shell.length).toBeGreaterThan(5);
    expect(shell.length).toBeLessThanOrEqual(30);
    expect(sw).toContain("cache.addAll(SHELL)");
    expect(sw).not.toContain("STATIC_ASSETS");
  });

  it("never precaches images, audio or whole pages (they are cached when first used)", () => {
    for (const f of shell) {
      expect(f, `${f} should not be in the install-time precache`).not.toMatch(
        /\.(png|jpe?g|webp|svg|mp3|mp4|jsonl)$|^pages\//
      );
    }
  });

  it("the shell is exactly what every page needs: the entry graph and the shared CSS", () => {
    const wanted = new Set(["index.html", "404.html", ...closure(["js/main.js"])]);
    for (const f of wanted) expect(shell, `${f} missing from the shell`).toContain(f);
    expect(shell).toContain("css/main.css");
    expect(shell).toContain("css/components.css");
    expect(shell.every((f) => existsSync(resolve(root, f)))).toBe(true);
  });

  it("is kept in step by the generator (run: node tools/sync-preloads.mjs)", () => {
    expect(run({ check: true })).not.toContain("sw.js");
  });
});

describe("campus book image loading", () => {
  const make = (n) =>
    Array.from({ length: n }, (_, i) => ({
      id: i + 1,
      club: "Campus_Archive",
      file_type: "image",
      aspect_ratio: 1.5,
      width: 1200,
      height: 800,
      category: `Cat${i % 5}`,
      category_label: `Place ${i % 5}`,
      title: `Library reading room ${i}`,
      public_url: `public/assets/processed/Campus_Archive/Cat${i % 5}/p${i}.webp`,
      thumb_url: `public/assets/processed/thumbs/Campus_Archive/Cat${i % 5}/p${i}.webp`,
    }));

  const bookImages = () => [...document.querySelectorAll("#campus-book img")];
  const loaded = () => bookImages().filter((img) => img.getAttribute("src"));

  it("fetches only the open spread and the next few pages, then more as it turns", async () => {
    document.body.innerHTML = '<div id="campus-book"></div>';
    const { initCampusBook } = await import("../../js/components/campus-book.js");
    initCampusBook(make(40));
    const total = bookImages().length;
    expect(total).toBeGreaterThanOrEqual(20); // a dozen plates, front and back
    const first = loaded().length;
    expect(first).toBeGreaterThan(0);
    // it used to be every one of them, eagerly
    expect(first).toBeLessThanOrEqual(Math.ceil(total / 2));

    document.querySelector(".book__flip--next").click();
    expect(loaded().length).toBeGreaterThan(first);
    expect(loaded().length).toBeLessThan(total);
  });

  it("never leaves a hydrated image half-built", () => {
    for (const img of loaded()) expect(img.hasAttribute("data-src")).toBe(false);
  });
});
